### ISSUE TITLE
Problem with card payment

### ISSUE THREAD

**Issue by Misiur** [HaxeSummit2017/organization#20]
Hi guys, I don't think this repo is a good place for this question but there is no other information about how to contact website maintainers. 

I wanted to buy a ticket, submitted the form, then my 3-d secure kicked in, I typed my password and I got "your session has timed out". I tried again, same result. I tried in other browser, and my hand slipped and I clicked cancel in 3-d secure window. I tried buying ticket again, and now it says that my card is declined due to CC processor security system.

What can I do? I only have one credit card, so I'm out of luck?

**Comment by back2dos** [comment]
Hiho. If credit card doesn't work for you, please contact Melanie.Delannoy@doclerholding.com to arrange for other means of payment. Sorry for the inconvenience :(

**Comment by Misiur** [comment]
Thanks
